module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: '.env',
        blacklist: null,
        whitelist: null,
        safe: false,
        allowUndefined: false,
      },
    ],
    [
      'module-resolver',
      {
        root: ['./src'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
        ],
        alias: {
          '@screens/common': './src/components/screens/common/index.ts',
          '@screens': './src/components/screens/index.ts',
          '@components': './src/components/common/index.ts',
          '@schema-types': './src/types/schema.ts',
          '@providers': './src/providers/index.ts',
          '@local-types': './src/types/index.ts',
          '@hooks': './src/hooks/index.ts',
          '@utils': './src/utils/index.ts',
          '@graphql': './src/graphql',
          '@routes': './src/routes',
          '@styles': './src/styles',
          '@i18n': './src/i18n',
          '@src': './src',
          '@dependencies': './package.json',
        },
      },
    ],
    'react-native-reanimated/plugin',
  ],
};
