export namespace Routes {
  export enum InitialScreenChecking {
    INITIAL_SCREEN = 'APP/INITIAL_SCREEN',
  }

  export enum Onboarding {
    ONBOARDING = 'APP/ONBOARDING',
  }

  export enum Tabs {
    TABS = 'APP/TABS',
    HOME = 'APP/TABS/HOME',
    FAMOUS = 'APP/TABS/FAMOUS',
    QUIZ = 'APP/TABS/QUIZ',
    NEWS = 'APP/TABS/NEWS',
  }

  export enum Home {
    HOME = 'APP/HOME',
    MEDIA_DETAILS_VIEW_ALL = 'APP/HOME/MEDIA_DETAILS_VIEW_ALL',
    IMAGES_GALLERY = 'APP/HOME/IMAGES_GALLERY',
    TV_SHOW_DETAILS = 'APP/HOME/TV_SHOW_DETAILS',
    TV_SHOW_SEASONS = 'APP/HOME/TV_SHOW/SEASONS',
    MOVIE_DETAILS = 'APP/HOME/MOVIE/DETAILS',
    FAMOUS_DETAILS = 'APP/HOME/FAMOUS/DETAILS',
    MEDIA_REVIEWS = 'APP/HOME/MEDIA_REVIEWS',
    SEARCH = 'APP/HOME/SEARCH',
  }

  export enum Famous {
    FAMOUS = 'APP/FAMOUS',
    DETAILS = 'APP/FAMOUS/DETAILS',
    IMAGES_GALLERY = 'APP/FAMOUS/IMAGES_GALLERY',
    TV_SHOW_DETAILS = 'APP/FAMOUS/TV_SHOW/DETAILS',
    TV_SHOW_SEASONS = 'APP/FAMOUS/TV_SHOW/SEASONS',
    MOVIE_DETAILS = 'APP/FAMOUS/MOVIE/DETAILS',
    MEDIA_REVIEWS = 'APP/FAMOUS/MEDIA_REVIEWS',
    SEARCH = 'APP/FAMOUS/SEARCH',
  }

  export enum Quiz {
    QUIZ = 'APP/QUIZ',
    SETUP_QUESTIONS = 'APP/QUIZ/SETUP_QUESTIONS',
    QUESTIONS = 'APP/QUIZ/QUESTIONS',
    RESULTS = 'APP/QUIZ/RESULTS',
  }

  export enum News {
    NEWS = 'APP/NEWS',
  }

  export enum Settings {
    SETTINGS = 'APP/SETTINGS',
    IMAGES_QUALITY = 'APP/SETTINGS/IMAGES_QUALITY',
    OPEN_SOURCE = 'APP/SETTINGS/OPEN_SOURCE',
    LANGUAGE = 'APP/SETTINGS/LANGUAGE',
    THEME = 'APP/SETTINGS/THEME',
    ABOUT = 'APP/SETTINGS/ABOUT',
  }
}
