const KEYS = {
  FIRST_TIME_RUNNING_APP: 'FIRST_TIME_RUNNING_APP',
  APP_STORAGE_KEY: '@CINE_TASTY',
  APP_THEME: 'APP_THEME',
  LANGUAGE: 'LANGUAGE',
};

const VALUES = {
  FALLBACK_LANGUAGE: 'en',
};

export default {
  VALUES,
  KEYS,
};
