name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: macos
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g react-native-cli
          npm install -g yarn
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Unit & Component Tests
        run: yarn test
