name: CI

on:
  pull_request:
    branches: [development, master]

jobs:
  ci-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Installing npm dependencies
        run: npm install

      - name: Running Prettier
        run: npm run prettier:fix

      - name: Running ESlint
        run: npm run lint:fix

      # - name: Building TS files
      #  run: npm run compile

      - name: Running tests
        run: npm run test
