name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, development]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Dependencies
        run: npm install

      - name: Running prettier
        run: npm run prettier:fix

      - name: Running eslint
        run: npm run lint:fix

      - name: Running tests
        run: npm run test
